spring:
    application:
        name: messaging

kafka:
    bootstrap-servers: localhost:9092
    topic:
        name: my-topic
    consumer:
        group-id: my-group

# ___ Configs ___
#spring:
#    kafka:
#        bootstrap-servers: localhost:9092
#        consumer:
#            group-id: my-group
#            auto-offset-reset: earliest
#        producer:
#            key-serializer: org.apache.kafka.common.serialization.StringSerializer
#            value-serializer: org.apache.kafka.common.serialization.StringSerializer